package com.crisdev.saludservice.enums;

public enum Especialidad {
    CARDIOLOGIA, //    CIRUGIA_GENERAL,
    //    CIRUGIA_MAXILOFACIAL,
//    CIRUGIA_PEDIATRICA,
    DERMATOLOGIA, NUTRICION, //    GINECOLOGIA_Y_OBSTETRICIA,
    HEMATOLOGIA, INFECTOLOGIA, //    MEDICINA_DE_FAMILIA,
    //    MEDICINA_GENERAL,
    TRAUMATOLOGIA, NEUROLOGIA, OFTALMOLOGIA, ONCOLOGIA, DIABETOLOGIA, PEDIATRIA
}

